name: CSIRO app container

env:
  IMAGE_NAME: csiro-node-app
  IMAGE_TAG: latest
  USERNAME: zzpz

on:
  release:
    types: [created]

jobs:
  build:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code 
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm install

    - name: Build application
      run: npm run build

# should probably be using the docker/build-push-action?
    - name: Build the Docker image
      run: docker build -t ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} -t docker.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .
    
    - name: Log in to the ghcr.io registry
      run: echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ env.USERNAME }} --password-stdin
    
    - name: Push the Docker image to the ghcr.io registry
      run: docker push ghcr.io/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}


# docker login action, push manually from CLI
    - name: Log in to Docker Hub registry
      uses: docker/login-action@v1
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PAT }}
    
    - name: Push the Docker image to Docker Hub
      run: docker push ${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}